#!/usr/bin/with-contenv bash
###############################################
#
#  Run filebeat
#
###############################################
FB_PATH=/usr/local/filebeat-"${FB_VERSION}"-linux-x86_64
chmod +x "${FB_PATH}"/filebeat
exec "${FB_PATH}"/filebeat