#!/usr/bin/with-contenv bash
###############################################
#
#  Run filebeat
#
###############################################
exec filebeat -e -c /etc/filebeat/filebeat.yml -path.home "${FB_PATH}"