filebeat.config.modules:
  path: ${FB_PATH}/modules.d/*.yml
  reload.enabled: false

filebeat.inputs:
  - type: docker
    exclude_files: ['\.gz$']
    containers.ids:
      - "*"
processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

output.elasticsearch:
  hosts: ["${EKHOST:?EKHOST is not defined!}:9200"]

setup.kibana.host: "${EKHOST:?EKHOST is not defined!}:5601"
setup.dashboards.directory: ${FB_PATH}/kibana/